dist: focal
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - sudo snap install hugo --channel=extended

script:
  - ./grabrepos.py
  - hugo
cache:
  pip: true
branches:
  only:
    - master
deploy:
  provider: pages
  repo: homieiot/homieiot.github.io
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
