name: Website CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install requirements
        run: |
            pip install -r requirements.txt
            wget https://github.com/gohugoio/hugo/releases/download/v0.102.3/hugo_extended_0.102.3_Linux-64bit.deb -O hugo.deb
            dpkg -i hugo.deb
      - name: Build Website
        run: |
            ./grabrepos.py
            hugo
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true